
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int llavecerrar = 6;
  public static final int tbool = 3;
  public static final int cadena = 21;
  public static final int llaveabrir = 7;
  public static final int decimal = 19;
  public static final int tfloat = 4;
  public static final int imprimir = 20;
  public static final int por = 14;
  public static final int tint = 2;
  public static final int tdouble = 5;
  public static final int menos = 13;
  public static final int div = 15;
  public static final int igual = 11;
  public static final int EOF = 0;
  public static final int parentesisabrir = 8;
  public static final int id = 17;
  public static final int potencia = 16;
  public static final int error = 1;
  public static final int entero = 18;
  public static final int parentesiscerrar = 9;
  public static final int mas = 12;
  public static final int puntoycoma = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tint",
  "tbool",
  "tfloat",
  "tdouble",
  "llavecerrar",
  "llaveabrir",
  "parentesisabrir",
  "parentesiscerrar",
  "puntoycoma",
  "igual",
  "mas",
  "menos",
  "por",
  "div",
  "potencia",
  "id",
  "entero",
  "decimal",
  "imprimir",
  "cadena"
  };
}

